server:
  port: 8081
  
spring:
  application:
    name: academy-service
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationSorter: method
    
---
spring:
  profiles: local, default
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/academy
    drivrClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:academy}   
    password: ${MYSQL_PASSWORD:AcademyPass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        storage_engine: innodb
    show-sql: true   
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true              
